version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/app
    command: python main.py & python -c "from scheduler import start_scheduler; start_scheduler()" & wait