version: '3'
services:
  web:
    container_name: trading-signal-web
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: python main.py
  schedule:
    container_name: trading-signal-schedule
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/app
    command: python scheduler.py